# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Therapist.create( name: 'Peter Parker', age: 25, gender: 'Male', bio: 'Hello, My name is Peter Parker, and I am a Therapist with specialty in dealing with Depression' )
Therapist.create( name: 'Mary Watson', age: 26, gender: 'Female', bio: 'Hello, My name is Mary Watson and I am a Therapist with specialty in dealing with Anxiety' )
Therapist.create( name: 'Eddie Brock', age: 31, gender: 'Male', bio: 'Hello, My name is Eddie Brock and I am a Therapist with specialty in dealing with Addictions' )
Therapist.create( name: 'Harry Osborn', age: 40, gender: 'Male', bio: 'Hello, My name is Harry Osborn, and I am a Therapist with specialty in dealing with Sexuality' )
Therapist.create( name: 'Gwen Stacy', age: 24, gender: 'Female', bio: 'Hello, My name is Gwen Stacy and I am a Therapist with specialty in dealing with Relationships' )

Specialty.create( name: 'Depression')
Specialty.create( name: 'Anxiety')
Specialty.create( name: 'Addiction')
Specialty.create( name: 'Sexuality')
Specialty.create( name: 'Relationships')

TherapistSpecialty.create( specialty_id: 1, therapist_id: 1 )
TherapistSpecialty.create( specialty_id: 2, therapist_id: 2 )
TherapistSpecialty.create( specialty_id: 3, therapist_id: 3 )
TherapistSpecialty.create( specialty_id: 4, therapist_id: 4 )
TherapistSpecialty.create( specialty_id: 5, therapist_id: 5 )

Question.create( description: 'Why are you looking for Therapy?' )
Question.create( description: 'How do you feel about your past?' )
Question.create( description: 'How do you feel about your present?' )
Question.create( description: 'How do you feel about your future?' )
Question.create( description: 'What is your biggest wish for your life?' )

Alternative.create( description: 'Because I am feeling sad, unmotivated, no energy', question_id: 1, specialty_id: 1 )
Alternative.create( description: 'Because I am feeling anxitey and fear', question_id: 1, specialty_id: 2 )
Alternative.create( description: 'Because I want to change habits or break addictions', question_id: 1, specialty_id: 3 )
Alternative.create( description: 'Because I have insecurity about myself', question_id: 1, specialty_id: 4 )
Alternative.create( description: 'Because I have relationship issues', question_id: 1, specialty_id: 5 )
Alternative.create( description: 'I feel a lot of sadness about my past, I hate it', question_id: 2, specialty_id: 1 )
Alternative.create( description: 'I am afraid the mistakes of my past will follow me forever', question_id: 2, specialty_id: 2 )
Alternative.create( description: 'I want to understand my past better', question_id: 2, specialty_id: 3 )
Alternative.create( description: 'I have some shame about my past', question_id: 2, specialty_id: 4 )
Alternative.create( description: 'I have issues with the people of my past', question_id: 2, specialty_id: 5 )
Alternative.create( description: 'I have very little motivation or happiness about my present situation', question_id: 3, specialty_id: 1 )
Alternative.create( description: 'My present situation gives me a lot of fear and anxiety', question_id: 3, specialty_id: 2 )
Alternative.create( description: 'I am not able to control my present situation', question_id: 3, specialty_id: 3 )
Alternative.create( description: 'I am not able to be myself', question_id: 3, specialty_id: 4 )
Alternative.create( description: 'I am not happy with my present relationships', question_id: 3, specialty_id: 5 )
Alternative.create( description: 'I am hopeless about my future', question_id: 4, specialty_id: 1 )
Alternative.create( description: 'I am afraid about my future', question_id: 4, specialty_id: 2 )
Alternative.create( description: 'I want to change my future', question_id: 4, specialty_id: 3 )
Alternative.create( description: 'I want to feel more free in my future', question_id: 4, specialty_id: 4 )
Alternative.create( description: 'I want better relationships in my future', question_id: 4, specialty_id: 5 )
Alternative.create( description: 'I want to be happy', question_id: 5, specialty_id: 1 )
Alternative.create( description: 'I want to be have peace', question_id: 5, specialty_id: 2 )
Alternative.create( description: 'I want to have control of my life', question_id: 5, specialty_id: 3 )
Alternative.create( description: 'I want to be confident and free', question_id: 5, specialty_id: 4 )
Alternative.create( description: 'I want to have healthy relationships', question_id: 5, specialty_id: 5 )
