# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Therapist.create( name: 'Roberto', age: 25, gender: 'Male', bio: 'Hello, My name is Peter Parker, and I am a Therapist with specialty in dealing with Depression', photo: 'https://optivius.com/img/testi-man.043bc168.png' )
Therapist.create( name: 'Fernanda', age: 26, gender: 'Female', bio: 'Hello, My name is Mary Watson and I am a Therapist with specialty in dealing with Anxiety', photo: 'https://4eqxrm3sl0u61595g420edx0-wpengine.netdna-ssl.com/wp-content/uploads/2021/08/approch_img.png' )
Therapist.create( name: 'André Souza', age: 31, gender: 'Male', bio: 'Hello, My name is Eddie Brock and I am a Therapist with specialty in dealing with Addictions', photo: 'https://img.freepik.com/free-photo/portrait-smiling-young-man-eyewear_171337-4842.jpg?t=st=1654645133~exp=1654645733~hmac=6854d39187f0bb0919abd8b58052c8dca53c44349484ea9b528ce1b7f27e2ca4&w=826' )
Therapist.create( name: 'Gustavo', age: 40, gender: 'Male', bio: 'Hello, My name is Harry Osborn, and I am a Therapist with specialty in dealing with Sexuality', photo: 'https://img.freepik.com/free-photo/portrait-successful-man-having-stubble-posing-with-broad-smile-keeping-arms-folded_171337-1267.jpg?t=st=1654645453~exp=1654646053~hmac=cede3e464a2a2de78e1440773dc144c2b52c159326d199909096494cca3824ef&w=826' )
Therapist.create( name: 'Gabriela', age: 24, gender: 'Female', bio: 'Hello, My name is Gwen Stacy and I am a Therapist with specialty in dealing with Relationships', photo: 'https://img.freepik.com/free-photo/good-advice-from-beautiful-woman_329181-3527.jpg?t=st=1654645196~exp=1654645796~hmac=ea78366c87f4281a245414a9d69324eaa5dd33642eda7b459616d2c63c5a3fc1&w=826' )

Specialty.create( name: 'Depression')
Specialty.create( name: 'Anxiety')
Specialty.create( name: 'Addiction')
Specialty.create( name: 'Sexuality')
Specialty.create( name: 'Relationships')

TherapistSpecialty.create( specialty_id: 1, therapist_id: 1 )
TherapistSpecialty.create( specialty_id: 2, therapist_id: 2 )
TherapistSpecialty.create( specialty_id: 3, therapist_id: 3 )
TherapistSpecialty.create( specialty_id: 4, therapist_id: 4 )
TherapistSpecialty.create( specialty_id: 5, therapist_id: 5 )

Question.create( description: 'Por que você está procurando por Terapia?' )
Question.create( description: 'Como você se sente a respeito do seu passado?' )
Question.create( description: 'Como você se sente a respeito do seu presente?' )
Question.create( description: 'Como você se sente a respeito do seu futuro?' )
Question.create( description: 'Qual é o seu maior desejo para a sua vida?' )

Alternative.create( description: 'Porque estou me sentindo triste, sem motivação e sem energia', question_id: 1, specialty_id: 1 )
Alternative.create( description: 'Porque estou sentindo ansiedade ou medo', question_id: 1, specialty_id: 2 )
Alternative.create( description: 'Porque eu quero mudar os meus hábitos ou vencer vícios', question_id: 1, specialty_id: 3 )
Alternative.create( description: 'Porque eu tenho inseguranças sobre mim mesmo', question_id: 1, specialty_id: 4 )
Alternative.create( description: 'Porque eu tenho problemas de relacionamentos', question_id: 1, specialty_id: 5 )
Alternative.create( description: 'Eu sinto muita tristeza a respeito do meu passado', question_id: 2, specialty_id: 1 )
Alternative.create( description: 'Eu temo que os erros do meu passado vão me seguir pra sempre', question_id: 2, specialty_id: 2 )
Alternative.create( description: 'Eu quero entender melhor o meu passado', question_id: 2, specialty_id: 3 )
Alternative.create( description: 'Eu tenho certas vergonhas a respeito do meu passado', question_id: 2, specialty_id: 4 )
Alternative.create( description: 'Eu tenho problemas com pessoas no meu passado', question_id: 2, specialty_id: 5 )
Alternative.create( description: 'Eu tenho pouca motivação ou felicidade sobre o meu presente', question_id: 3, specialty_id: 1 )
Alternative.create( description: 'Minha situação atual me causa muito medo e ansiedade', question_id: 3, specialty_id: 2 )
Alternative.create( description: 'Eu não consigo controlar a minha situação atual', question_id: 3, specialty_id: 3 )
Alternative.create( description: 'Eu não consigo ser eu mesmo', question_id: 3, specialty_id: 4 )
Alternative.create( description: 'Eu não estou feliz com os meus relacionamentos atuais', question_id: 3, specialty_id: 5 )
Alternative.create( description: 'Eu estou sem esperança a respeito do meu futuro', question_id: 4, specialty_id: 1 )
Alternative.create( description: 'Eu tenho medo do meu futuro', question_id: 4, specialty_id: 2 )
Alternative.create( description: 'Eu quero mudar o meu futuro', question_id: 4, specialty_id: 3 )
Alternative.create( description: 'Eu quero me sentir mais livre no meu futuro', question_id: 4, specialty_id: 4 )
Alternative.create( description: 'Eu quero ter melhores relacionamentos no meu futuro', question_id: 4, specialty_id: 5 )
Alternative.create( description: 'Eu quero ser feliz', question_id: 5, specialty_id: 1 )
Alternative.create( description: 'Eu quero ter paz', question_id: 5, specialty_id: 2 )
Alternative.create( description: 'Eu quero ter controle sobre a minha vida', question_id: 5, specialty_id: 3 )
Alternative.create( description: 'Eu quero ser seguro sobre mim mesmo e livre', question_id: 5, specialty_id: 4 )
Alternative.create( description: 'Eu quero ter relacionamentos saudáveis', question_id: 5, specialty_id: 5 )
